feat: add arrow thin style
naver/egjs-flicking-plugins pull request #38
Opened 2022-05-30 13:22 UTC by RudyBlack

## Details
I think need a thin arrow. So add a thin arrow style with class.

2022-05-30 13:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/naver/egjs-flicking-plugins?pullRequest=38) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/naver/egjs-flicking-plugins?pullRequest=38) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/naver/egjs-flicking-plugins?pullRequest=38) it.</sub>

2022-06-02 01:35 UTC, WoodNeck approved these changes

2022-06-02 01:35 UTC, WoodNeck commented on css/arrow.css
> +.flicking-arrow-next.thin::after{
As other modifier classes are using names like `is-xxx`, this should be also changed like that.

```suggestion
.flicking-arrow-prev.is-thin::before,
.flicking-arrow-prev.is-thin::after,
.flicking-arrow-next.is-thin::before,
.flicking-arrow-next.is-thin::after{
  height: 3px;
}

.flicking-arrow-prev.is-thin::after,
.flicking-arrow-next.is-thin::after{
```

2022-06-02 01:35 UTC, WoodNeck commented on css/arrow.css
> +  top : calc(50% - 2px);
Please remove the space between `top` and `:`

```suggestion
  top: calc(50% - 2px);
```

2022-06-02 01:37 UTC, WoodNeck requested changes
Thanks for the PR!
I think I can agree that we need more default styles for those plugins.
It would be nice for you to include how they actually look like.

![image](https://user-images.githubusercontent.com/26213435/171528419-58b49881-e5c3-4596-945c-c71453ec807a.png)

2022-06-02 10:49 UTC, WoodNeck approved these changes

2022-06-02 11:01 UTC, daybrush approved these changes
LGTM

2022-06-02 11:16 UTC, malangfox approved these changes
LGTM

2022-06-03 02:23 UTC, merged